services:
    php-fpm:
        build: docker\php-fpm
        ports:
            - 9000:9000
        volumes:
            - ./project:/var/www/html
    nginx:
        depends_on:
            - php-fpm
        build: docker\nginx
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./project:/var/www/html
        environment:
            - APP_ENV=local