services:
    php-fpm:
        build:
            context: docker/php-fpm
            args:
                USER_ID: 1000
                GROUP_ID: 1000
        privileged: true
        ports:
            - 9001:9001
        volumes:
            - ./project:/var/www/html:delegated

    nginx:
        depends_on:
            - php-fpm
        build:
            context: docker/nginx
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./project:/var/www/html:cached
        environment:
            - APP_ENV=local
