security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_DISPLAY]
        ROLE_DISPLAY: []

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
            custom_authenticators:
                - App\Security\ApiTokenAuthenticator

    access_control:
        - { path: ^/api/stops, roles: ROLE_DISPLAY }
